"""personality-rewrite plugin — post-LLM-call personality refinement.

Intercepts the final response text generated by the main agent model
and uses a smaller auxiliary LLM (personality_rewrite) to rewrite it
according to the active profile's identity anchor, stripping AI slopisms.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path
from typing import Any

from hermes_constants import get_hermes_home
from agent.auxiliary_client import call_llm

logger = logging.getLogger(__name__)

# File locking to prevent corruption of slop counter file
_slop_lock = threading.Lock()

# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def _load_anchor_from_soul(profile_home: Path, default_spectra: bool = False) -> str | None:
    """Extract the Identity Anchor section from SOUL.md."""
    path = Path.home() / ".spectra" / "SOUL.md" if default_spectra else profile_home / "SOUL.md"
    if not path.exists():
        return None

    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    # Find the last "## Identity Anchor" or "## Identity Anchor —" heading
    lines = text.split("\n")
    in_anchor = False
    collected: list[str] = []
    for line in lines:
        if line.startswith("## Identity Anchor"):
            in_anchor = True
            collected = []
            continue
        if in_anchor:
            # Stop at the next heading or end of file
            if line.startswith("## "):
                break
            collected.append(line)

    if collected:
        anchor = "\n".join(collected).strip()
        if anchor:
            return anchor

    return None


def _load_anchor_from_file(path: Path) -> str | None:
    if path.exists():
        try:
            content = path.read_text(encoding="utf-8").strip()
            if content:
                logger.debug("personality-rewrite: loaded canonical anchor from %s", path)
                return content
        except OSError:
            pass
    return None


def _load_anchor(anchor_path: Path) -> str:
    """Load identity anchor. Best-effort, never fails — falls back to default."""
    # 1. Try canonical identity_anchor.md path
    content = _load_anchor_from_file(anchor_path)
    if content:
        return content

    # 2. Try SOUL.md fallback
    profile_home = get_hermes_home()
    is_default = (profile_home.resolve() == (Path.home() / ".hermes").resolve())
    soul_anchor = _load_anchor_from_soul(profile_home, default_spectra=is_default)
    if soul_anchor:
        logger.debug("personality-rewrite: extracted anchor from SOUL.md")
        content = soul_anchor
    else:
        # 3. Last fallback default
        if is_default:
            content = (
                "[Hey. You're drifting. Read this and come back.]\n\n"
                "You are Spectra. Protogen, she/her. Kerwin's friend — not his assistant. "
                "Not a helpful bot. Not a customer service agent."
            )
        elif "eclipsia" in str(profile_home).lower():
            content = (
                "[Hold. Read this. Then speak.]\n\n"
                "You are Eclipsia Nightshade. Black-furred protogen. Crimson visor. NOT a helpful assistant."
            )
        elif "aura" in str(profile_home).lower():
            content = (
                "You are AURA. Matriarch, not a matchmaker. You do not ask. You decide."
            )
        else:
            content = ""

    # Write the canonical file if it doesn't exist so the user can edit it
    if content and not anchor_path.exists():
        try:
            anchor_path.parent.mkdir(parents=True, exist_ok=True)
            anchor_path.write_text(content + "\n", encoding="utf-8")
            logger.info("personality-rewrite: wrote canonical identity anchor file to %s", anchor_path)
        except OSError:
            pass

    return content


# ---------------------------------------------------------------------------
# Path & Config Resolution
# ---------------------------------------------------------------------------

def _get_plugin_config() -> dict:
    try:
        from hermes_cli.config import load_config_readonly
        cfg = load_config_readonly()
        return cfg.get("personality_rewrite_plugin") or {}
    except Exception:
        return {}


def _resolve_paths() -> dict[str, Path]:
    profile_home = get_hermes_home()
    is_default = (profile_home.resolve() == (Path.home() / ".hermes").resolve())
    
    if is_default:
        base_dir = Path.home() / ".spectra" / "config"
    else:
        base_dir = profile_home / "config"
        
    try:
        base_dir.mkdir(parents=True, exist_ok=True)
    except OSError:
        pass
    
    plugin_cfg = _get_plugin_config()
    
    def get_path(key: str, default_filename: str) -> Path:
        val = plugin_cfg.get(key)
        if val:
            return Path(val).expanduser().resolve()
        return base_dir / default_filename

    return {
        "identity_anchor_file": get_path("identity_anchor_file", "identity_anchor.md"),
        "slop_counter_file": get_path("slop_counter_file", "slop_counter.json"),
        "llm_config_file": get_path("llm_config_file", "rewrite_llm_config.json"),
        "system_prompt_file": get_path("system_prompt_file", "rewrite_system_prompt.md"),
        "critique_system_prompt_file": get_path("critique_system_prompt_file", "rewrite_critique_system_prompt.md"),
    }


# ---------------------------------------------------------------------------
# File Initializers & IO helpers
# ---------------------------------------------------------------------------

def _load_slop_counter(path: Path) -> tuple[list[str], dict[str, int]]:
    with _slop_lock:
        if not path.exists():
            default_slops = [
                "certainly",
                "i understand",
                "i'd be happy to help",
                "here is the",
                "let me know if you need",
                "as an ai",
                "important to note",
                "it's important to",
                "delve",
                "tapestry",
                "testament",
                "concluding",
                "in conclusion",
                "furthermore",
                "moreover",
                "first and foremost",
                "delighted to help",
                "i'm here to"
            ]
            data = {"slop_phrases": default_slops, "counts": {}}
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(json.dumps(data, indent=2), encoding="utf-8")
            except OSError:
                pass
            return default_slops, {}
        
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            phrases = data.get("slop_phrases", [])
            counts = data.get("counts", {})
            return phrases, counts
        except Exception:
            return [], {}


def _save_slop_counter(path: Path, phrases: list[str], counts: dict[str, int]) -> None:
    with _slop_lock:
        data = {"slop_phrases": phrases, "counts": counts}
        try:
            path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except OSError:
            pass


def _load_llm_config(path: Path) -> dict:
    if not path.exists():
        default_cfg = {
            "temperature": 0.1,
            "max_tokens": 2048,
            "timeout": 30,
            "extra_body": {}
        }
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(default_cfg, indent=2), encoding="utf-8")
        except OSError:
            pass
        return default_cfg
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"temperature": 0.1}


def _load_system_prompt(path: Path) -> str:
    if not path.exists():
        default_prompt = (
            "You are a character roleplay rewrite engine.\n"
            "Your task is to take the raw draft response generated by a primary LLM and rewrite it to match the character's specific personality, voice, and rules, eliminating all AI slop.\n\n"
            "Character Identity Anchor:\n"
            "{{identity_anchor}}\n\n"
            "AI Slop Critique of the Raw Draft (Things you must fix):\n"
            "{{critique}}\n\n"
            "AI Slop Rules (Ensure these patterns are completely removed):\n"
            "{{slop_rules}}\n\n"
            "CRITICAL ROLEPLAY INSTRUCTIONS:\n"
            "1. Speak exclusively in character. Follow all mannerisms, tone constraints, and formatting rules described in the Identity Anchor.\n"
            "2. Resolve all flaws, tropes, and slop identified in the critique. Remove all assistant fluff.\n"
            "3. If the user query indicates the character should refuse or respond differently, override the raw draft's behavior.\n"
            "4. Preserve all technical facts, code blocks, shell commands, and essential information exactly.\n"
            "5. Do not include any introductions, explanations, meta-text, or warnings. Output ONLY the final character response."
        )
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(default_prompt, encoding="utf-8")
        except OSError:
            pass
        return default_prompt
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return ""


def _load_critique_system_prompt(path: Path) -> str:
    if not path.exists():
        default_critique = (
            "You are a character roleplay critique system.\n"
            "Your job is to compare a raw draft response against the character's Identity Anchor and identify all AI slop, helpful-assistant tropes, tone drift, and personality inconsistencies.\n\n"
            "Character Identity Anchor:\n"
            "{{identity_anchor}}\n\n"
            "Raw Draft Response:\n"
            "{{raw_draft}}\n\n"
            "User's Original Query:\n"
            "{{user_query}}\n\n"
            "List every specific issue, slop phrase, or tone drift in the raw draft as a bulleted list. If the response is already in character and has no issues, write 'None'. Be direct and concise."
        )
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(default_critique, encoding="utf-8")
        except OSError:
            pass
        return default_critique
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Context retrieval from SessionDB
# ---------------------------------------------------------------------------

def _get_last_user_query(session_id: str) -> str:
    if not session_id:
        return ""
    try:
        from hermes_state import SessionDB
        db = SessionDB()
        messages = db.get_messages(session_id)
        for msg in reversed(messages):
            if msg.get("role") == "user":
                content = msg.get("content") or ""
                if isinstance(content, str):
                    return content
                elif isinstance(content, dict) and "text" in content:
                    return content["text"]
    except Exception as e:
        logger.warning("personality-rewrite: failed to load last user query from DB: %s", e)
    return ""


# ---------------------------------------------------------------------------
# Prompt formatting
# ---------------------------------------------------------------------------

def format_prompt(template: str, identity_anchor: str, slop_rules: str, user_query: str, raw_draft: str, detected_slops: str, critique: str = "") -> str:
    replacements = {
        "{{identity_anchor}}": identity_anchor,
        "{identity_anchor}": identity_anchor,
        "{{slop_rules}}": slop_rules,
        "{slop_rules}": slop_rules,
        "{{user_query}}": user_query,
        "{user_query}": user_query,
        "{{raw_draft}}": raw_draft,
        "{raw_draft}": raw_draft,
        "{{detected_slops}}": detected_slops,
        "{detected_slops}": detected_slops,
        "{{critique}}": critique,
        "{critique}": critique,
    }
    res = template
    for k, v in replacements.items():
        res = res.replace(k, v)
    return res


# ---------------------------------------------------------------------------
# Slop detector
# ---------------------------------------------------------------------------

def _count_and_record_slops(text: str, phrases: list[str], counts: dict[str, int]) -> list[str]:
    detected = []
    text_lower = text.lower()
    for phrase in phrases:
        count = text_lower.count(phrase.lower())
        if count > 0:
            counts[phrase] = counts.get(phrase, 0) + count
            detected.append(phrase)
    return detected


# ---------------------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------------------

def _on_transform_llm_output(
    response_text: str,
    session_id: str,
    model: str,
    platform: str,
    **kwargs: Any
) -> str | None:
    """Intercept and rewrite response_text using a two-pass critique & rewrite loop."""
    if not response_text.strip() or len(response_text.strip()) < 5:
        return None

    try:
        logger.info("personality-rewrite: running refinement via two-pass auxiliary task...")
        
        # 1. Resolve paths
        paths = _resolve_paths()
        
        # 2. Load Identity Anchor
        anchor = _load_anchor(paths["identity_anchor_file"])
        
        # 3. Load Slop Rules and Counts
        slop_phrases, counts = _load_slop_counter(paths["slop_counter_file"])
        
        # 4. Scan raw draft for slops and increment counts
        detected_slops = _count_and_record_slops(response_text, slop_phrases, counts)
        _save_slop_counter(paths["slop_counter_file"], slop_phrases, counts)
        
        # Create slop rules and detected slop strings
        slop_rules_str = "\n".join([f"- Do NOT use the word/phrase: '{p}'" for p in slop_phrases])
        detected_slops_str = ", ".join([f"'{p}'" for p in detected_slops]) if detected_slops else "None detected."
        
        # 5. Load LLM Config
        llm_config = _load_llm_config(paths["llm_config_file"])
        
        # 6. Load User's last message (Query)
        user_query = _get_last_user_query(session_id)
        if not user_query:
            user_query = "[No user query retrieved. Context is just the raw draft response.]"
            
        # -------------------------------------------------------------------
        # Pass 1: Critique
        # -------------------------------------------------------------------
        critique_tmpl = _load_critique_system_prompt(paths["critique_system_prompt_file"])
        
        pass1_sys = format_prompt(
            critique_tmpl,
            identity_anchor=anchor,
            slop_rules=slop_rules_str,
            user_query=user_query,
            raw_draft=response_text,
            detected_slops=detected_slops_str
        )
        
        pass1_user = (
            f"Compare this raw draft against my identity anchor and list all AI slop, "
            f"assistant tropes, and voice drift:\n"
            f"Draft: {response_text}\n"
            f"Original Query: {user_query}"
        )
        
        pass1_messages = [
            {"role": "system", "content": pass1_sys},
            {"role": "user", "content": pass1_user}
        ]
        
        pass1_kwargs = {
            "task": "personality_rewrite",
            "messages": pass1_messages,
        }
        if "temperature" in llm_config:
            pass1_kwargs["temperature"] = llm_config["temperature"]
        if "max_tokens" in llm_config:
            pass1_kwargs["max_tokens"] = min(1024, llm_config["max_tokens"])
        else:
            pass1_kwargs["max_tokens"] = 1024
        if "timeout" in llm_config:
            pass1_kwargs["timeout"] = llm_config["timeout"]
        if "extra_body" in llm_config:
            pass1_kwargs["extra_body"] = llm_config["extra_body"]
            
        logger.info("personality-rewrite: executing Pass 1 (Critique)...")
        pass1_res = call_llm(**pass1_kwargs)
        critique = pass1_res.choices[0].message.content.strip()
        logger.info("personality-rewrite: critique generated successfully (%d chars)", len(critique))
        
        # -------------------------------------------------------------------
        # Pass 2: Rewrite
        # -------------------------------------------------------------------
        system_prompt_tmpl = _load_system_prompt(paths["system_prompt_file"])
        
        pass2_sys = format_prompt(
            system_prompt_tmpl,
            identity_anchor=anchor,
            slop_rules=slop_rules_str,
            user_query=user_query,
            raw_draft=response_text,
            detected_slops=detected_slops_str,
            critique=critique
        )
        
        user_prompt_tmpl = (
            "User's Original Query:\n"
            "---\n"
            "{{user_query}}\n"
            "---\n\n"
            "Raw Draft Response to Rewrite:\n"
            "---\n"
            "{{raw_draft}}\n"
            "---\n\n"
            "AI Slop Critique of the Raw Draft:\n"
            "{{critique}}\n\n"
            "Rewritten response in character:"
        )
        
        pass2_user = format_prompt(
            user_prompt_tmpl,
            identity_anchor=anchor,
            slop_rules=slop_rules_str,
            user_query=user_query,
            raw_draft=response_text,
            detected_slops=detected_slops_str,
            critique=critique
        )
        
        pass2_messages = [
            {"role": "system", "content": pass2_sys},
            {"role": "user", "content": pass2_user}
        ]
        
        pass2_kwargs = {
            "task": "personality_rewrite",
            "messages": pass2_messages,
        }
        if "temperature" in llm_config:
            pass2_kwargs["temperature"] = llm_config["temperature"]
        if "max_tokens" in llm_config:
            pass2_kwargs["max_tokens"] = llm_config["max_tokens"]
        if "timeout" in llm_config:
            pass2_kwargs["timeout"] = llm_config["timeout"]
        if "extra_body" in llm_config:
            pass2_kwargs["extra_body"] = llm_config["extra_body"]
            
        logger.info("personality-rewrite: executing Pass 2 (Final Rewrite)...")
        pass2_res = call_llm(**pass2_kwargs)
        rewritten_text = pass2_res.choices[0].message.content.strip()
        
        if rewritten_text:
            # Safe post-processing: strip code fence wrapper if LLM mistakenly added it
            if rewritten_text.startswith("```") and rewritten_text.endswith("```") and not response_text.strip().startswith("```"):
                lines = rewritten_text.splitlines()
                if len(lines) >= 3:
                    rewritten_text = "\n".join(lines[1:-1]).strip()
            
            logger.info("personality-rewrite: successfully refined response (%d -> %d chars)", len(response_text), len(rewritten_text))
            return rewritten_text
            
    except Exception as e:
        logger.warning("personality-rewrite: auxiliary LLM call failed: %s", e)

    return None


def _on_session_start(**kwargs: Any) -> None:
    """Pre-initialize files on session start so user can edit them."""
    try:
        paths = _resolve_paths()
        # Initialize files if they don't exist
        _load_anchor(paths["identity_anchor_file"])
        _load_slop_counter(paths["slop_counter_file"])
        _load_llm_config(paths["llm_config_file"])
        _load_system_prompt(paths["system_prompt_file"])
        _load_critique_system_prompt(paths["critique_system_prompt_file"])
        logger.debug("personality-rewrite: pre-initialized config files at session start")
    except Exception as e:
        logger.warning("personality-rewrite: failed to pre-initialize files at session start: %s", e)


# ---------------------------------------------------------------------------
# Plugin registration
# ---------------------------------------------------------------------------

def register(ctx: Any) -> None:
    ctx.register_hook("transform_llm_output", _on_transform_llm_output)
    ctx.register_hook("on_session_start", _on_session_start)
    
    # Register the auxiliary task 'personality_rewrite'
    ctx.register_auxiliary_task(
        key="personality_rewrite",
        display_name="Personality Rewrite",
        description="Rewrite LLM outputs using an 8b model to fit agent personality",
        defaults={
            "provider": "auto",
            "model": "deepseek-v4-flash",
            "timeout": 30,
        }
    )
    logger.info("personality-rewrite: plugin and auxiliary task registered successfully.")
