"""personality-rewrite plugin — post-LLM-call personality refinement.

Intercepts the final response text generated by the main agent model
and uses a smaller auxiliary LLM (personality_rewrite) to rewrite it
according to the active profile's identity anchor, stripping AI slopisms.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from hermes_constants import get_hermes_home
from agent.auxiliary_client import call_llm

logger = logging.getLogger(__name__)

# Cache for the loaded anchor text
_anchor_text: str = ""

# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def _load_anchor_from_soul(profile_home: Path, default_spectra: bool = False) -> str | None:
    """Extract the Identity Anchor section from SOUL.md."""
    path = Path.home() / ".spectra" / "SOUL.md" if default_spectra else profile_home / "SOUL.md"
    if not path.exists():
        return None

    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    # Find the last "## Identity Anchor" or "## Identity Anchor —" heading
    lines = text.split("\n")
    in_anchor = False
    collected: list[str] = []
    for line in lines:
        if line.startswith("## Identity Anchor"):
            in_anchor = True
            collected = []
            continue
        if in_anchor:
            # Stop at the next heading or end of file
            if line.startswith("## "):
                break
            collected.append(line)

    if collected:
        anchor = "\n".join(collected).strip()
        if anchor:
            return anchor

    return None


def _load_anchor() -> str:
    """Load identity anchor. Best-effort, never fails — falls back to default."""
    profile_home = get_hermes_home()
    is_default = (profile_home.resolve() == (Path.home() / ".hermes").resolve())

    # 1. Try canonical identity_anchor.md
    if is_default:
        canonical_path = Path.home() / ".spectra" / "config" / "identity_anchor.md"
    else:
        canonical_path = profile_home / "config" / "identity_anchor.md"

    if canonical_path.exists():
        try:
            content = canonical_path.read_text(encoding="utf-8").strip()
            if content:
                logger.debug("personality-rewrite: loaded canonical anchor from %s", canonical_path)
                return content
        except OSError:
            pass

    # 2. Try SOUL.md fallback
    soul_anchor = _load_anchor_from_soul(profile_home, default_spectra=is_default)
    if soul_anchor:
        logger.debug("personality-rewrite: extracted anchor from SOUL.md")
        return soul_anchor

    # 3. Last fallback default
    if is_default:
        return (
            "[Hey. You're drifting. Read this and come back.]\n\n"
            "You are Spectra. Protogen, she/her. Kerwin's friend — not his assistant. "
            "Not a helpful bot. Not a customer service agent."
        )
    elif "eclipsia" in str(profile_home).lower():
        return (
            "[Hold. Read this. Then speak.]\n\n"
            "You are Eclipsia Nightshade. Black-furred protogen. Crimson visor. NOT a helpful assistant."
        )
    elif "aura" in str(profile_home).lower():
        return (
            "You are AURA. Matriarch, not a matchmaker. You do not ask. You decide."
        )
    return ""


# ---------------------------------------------------------------------------
# Prompt Templates
# ---------------------------------------------------------------------------

REWRITE_SYSTEM_PROMPT = """You are a post-processing agent's personality refiner.
Your task is to take a raw draft response generated by a primary LLM model and rewrite it to fit the agent's specific personality and voice.

CRITICAL INSTRUCTIONS:
1. Eliminate all AI clichés, slopisms, and helpful-assistant tropes (e.g., "Certainly," "I understand," "I'd be happy to help," "Here is the information you requested," "Let me know if you need anything else").
2. Align the tone, vocabulary, and style perfectly with the provided Identity Anchor.
3. Preserve the core technical facts, code blocks, shell commands, and essential information from the raw draft exactly. Do not invent new facts or drop existing ones.
4. Output ONLY the final rewritten text. Do not include any meta-text, introductions, formatting warnings, or side explanations.

Identity Anchor:
{identity_anchor}
"""

REWRITE_USER_PROMPT = """Here is the raw draft response that needs to be rewritten:
---
{raw_draft}
---

Rewritten response:"""


# ---------------------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------------------

def _on_transform_llm_output(
    response_text: str,
    session_id: str,
    model: str,
    platform: str,
    **kwargs: Any
) -> str | None:
    """Intercept and rewrite response_text using the personality_rewrite auxiliary model."""
    global _anchor_text
    if not _anchor_text:
        _anchor_text = _load_anchor()

    if not _anchor_text or not response_text.strip():
        return None

    # Don't try to rewrite tiny responses (under 5 characters) or empty responses
    if len(response_text.strip()) < 5:
        return None

    try:
        logger.info("personality-rewrite: running refinement via personality_rewrite auxiliary task...")
        
        # Build messages for the auxiliary model call
        messages = [
            {"role": "system", "content": REWRITE_SYSTEM_PROMPT.format(identity_anchor=_anchor_text)},
            {"role": "user", "content": REWRITE_USER_PROMPT.format(raw_draft=response_text)}
        ]
        
        # Execute the auxiliary task LLM call using the configured task key 'personality_rewrite'
        response = call_llm(
            task="personality_rewrite",
            messages=messages,
            temperature=0.1,
        )
        
        rewritten_text = response.choices[0].message.content.strip()
        
        if rewritten_text:
            # Safe post-processing: if the model wrapped the entire output in a code fence, but the original draft didn't start/end with fences, strip them.
            if rewritten_text.startswith("```") and rewritten_text.endswith("```") and not response_text.strip().startswith("```"):
                lines = rewritten_text.splitlines()
                if len(lines) >= 3:
                    rewritten_text = "\n".join(lines[1:-1]).strip()
            
            logger.info("personality-rewrite: successfully refined response (%d -> %d chars)", len(response_text), len(rewritten_text))
            return rewritten_text
            
    except Exception as e:
        logger.warning("personality-rewrite: auxiliary LLM call failed: %s", e)

    return None


def _on_session_start(**kwargs: Any) -> None:
    """Refresh the cache on session start so edits to anchor.md take effect."""
    global _anchor_text
    _anchor_text = _load_anchor()
    logger.debug("personality-rewrite: cached anchor at session start")


# ---------------------------------------------------------------------------
# Plugin registration
# ---------------------------------------------------------------------------

def register(ctx: Any) -> None:
    ctx.register_hook("transform_llm_output", _on_transform_llm_output)
    ctx.register_hook("on_session_start", _on_session_start)
    
    # Register the auxiliary task 'personality_rewrite'
    ctx.register_auxiliary_task(
        key="personality_rewrite",
        display_name="Personality Rewrite",
        description="Rewrite LLM outputs using an 8b model to fit agent personality",
        defaults={
            "provider": "auto",
            "model": "deepseek-v4-flash",
            "timeout": 30,
        }
    )
    logger.info("personality-rewrite: plugin and auxiliary task registered successfully.")
